### ISSUE TITLE
Running on MacOS?

### ISSUE THREAD

**Issue by Tangston311** [DamianMehers/homebridge-alexa#2]
This may be an ignorant question because I'm new to all of this, but I have my Homebridge instance running on MacOS, not a Pi, but I can't get it to recognize my Alexa devices (I get the error below).  Could this work on a Mac or do I need a Pi to properly clone the repository (which, by the way, I've never done before so I have no idea if I'm doing it properly).

Also, could this support Alexa scenes perchance?  I.e. some of my compatible Alexa skills only create a scene, not a device, and I'm hoping to control those via Homekit.

Thanks!
Guthrie

/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Dining Room Lights' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by Tangston311** [comment]
Any help on this would be greatly appreciated.  Still can't get it to run on my Mac with the same error as above.  Thanks much.
